// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjNPO7CZW7m-LLU5BES5TuZbMj3QLIRo',
    appId: '1:994541066149:web:9b36e5721572823e513a4c',
    messagingSenderId: '994541066149',
    projectId: 'taskapp-34d5c',
    authDomain: 'taskapp-34d5c.firebaseapp.com',
    storageBucket: 'taskapp-34d5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33WnRJTOdnG5BVddeFX1eqkMXSShJj8c',
    appId: '1:994541066149:android:2a9987d4bdcc3e48513a4c',
    messagingSenderId: '994541066149',
    projectId: 'taskapp-34d5c',
    storageBucket: 'taskapp-34d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkY70zg8ms4fmmWC3-Xx-LWPHCHes9fU',
    appId: '1:994541066149:ios:f79eb5ebe73d2b5c513a4c',
    messagingSenderId: '994541066149',
    projectId: 'taskapp-34d5c',
    storageBucket: 'taskapp-34d5c.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica',
  );
}
